FILES = P0.rvm  P1.rvm  P2.rvm  P3.rvm  P4.rvm \
	        P6.rvm          P8.rvm  P9.rvm \
        P10.rvm P11.rvm P12.rvm \
	P15.rvm P16.rvm P17.rvm P18.rvm P19.rvm \
	P20.rvm P21.rvm         P23.rvm P24.rvm \
                P26.rvm         P28.rvm P29.rvm \
	P30.rvm P31.rvm P32.rvm P33.rvm P34.rvm \
	P35.rvm P36.rvm P37.rvm P38.rvm \
        \
	        P46.rvm P47.rvm P48.rvm \
                P51.rvm P52.rvm

all:
	rv-monitor ${FILES}
